index_img: /img/top.jpeg

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单: /list/ ||fa fa-heartbeat
  音乐: /music/ || fas fa-music
  照片: /gallery/ || fas fa-images
  电影: /movies/ || fas fa-video
  友鏈: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

avatar:
  img: /img/avatar.png

social:
  fa-brands fa-weibo: https://weibo.com/u/1693984303 || 一只仙鱼
  fa-brands fa-tiktok: https://weibo.com/u/1693984303 || 抖音

inject:
  head:
  - <link rel="stylesheet" href="//at.alicdn.com/t/font_3186016_p4u9kjrvhh.css">

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false

# 好看的綵帶背景，會飄動
canvas_fluttering_ribbon:
  enable: true
  mobile: false # false 手機端不顯示 true 手機端顯示

# 點擊出現文字，文字可自行修改
ClickShowText:
  enable: true
  text:
    - 含宝
    - 憨包
    - 李霸蛮
    - 李大碗
  fontSize: 15px
  random: false # 文字隨機顯示
  mobile: false

# 美化頁面顯示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

# Global font settings
# Don't modify the following settings unless you know how they work (非必要不要修改)
font:
  global-font-size:
  code-font-size:
  font-family: Butterfly, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif
  code-font-family: Butterfly, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

# Font settings for the site title and site subtitle
# 左上角網站名字 主頁居中網站名字
blog_title_font:
  font_link: https://yuhan-oss.oss-cn-shenzhen.aliyuncs.com/font.css
  font-family: Butterfly, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

# 主頁subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循環打字)
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 今日事&#44;今日畢
    - Never put off till tomorrow what you can do today

# Chat Button [recommend]
# It will create a button in the bottom right corner of website, and hide the origin button
chat_btn: true

# chatra
# https://chatra.io/
chatra:
  enable: true
  id: XpQNTkDyPa7SN3oMn

highlight_theme: darker